In [ ]:
import pandas as pd
import numpy as np 
import matplotlib.pyplot as plt

In [113]:
data = pd.read_csv('../dataset/car_prices.csv')
data.head()

,year,make,model,trim,body,transmission,vin,state,condition,odometer,color,interior,seller,mmr,sellingprice,saledate
0,2015,Kia,Sorento,LX,SUV,automatic,5xyktca69fg566472,ca,5.0,16639.0,white,black,kia motors america inc,20500.0,21500.0,Tue Dec 16 2014 12:30:00 GMT-0800 (PST)
1,2015,Kia,Sorento,LX,SUV,automatic,5xyktca69fg561319,ca,5.0,9393.0,white,beige,kia motors america inc,20800.0,21500.0,Tue Dec 16 2014 12:30:00 GMT-0800 (PST)
2,2014,BMW,3 Series,328i SULEV,Sedan,automatic,wba3c1c51ek116351,ca,45.0,1331.0,gray,black,financial services remarketing (lease),31900.0,30000.0,Thu Jan 15 2015 04:30:00 GMT-0800 (PST)
3,2015,Volvo,S60,T5,Sedan,automatic,yv1612tb4f1310987,ca,41.0,14282.0,white,black,volvo na rep/world omni,27500.0,27750.0,Thu Jan 29 2015 04:30:00 GMT-0800 (PST)
4,2014,BMW,6 Series Gran Coupe,650i,Sedan,automatic,wba6b2c57ed129731,ca,43.0,2641.0,gray,black,financial services remarketing (lease),66000.0,67000.0,Thu Dec 18 2014 12:30:00 GMT-0800 (PST)

data.loc[row , column] - row and column can be string 
data.iloc[row , column] - int type for row and column 
data.loc[0] : first row of the dataFrame with any column 
data.loc[[0,1,5]] : row 0 , 1 and 5 with any column 
data.loc[0:10] : first 11 rows (index 0 to 10 ) 
data.loc[: , ["model", "body"] ] : model and body column for all rows 
data.loc[:10] , "model"] : first 11 rows (0 to 10) for column model
data.iloc[0:10] : first 10 rows (index 0 to 9)

In [ ]:
data.loc[2:10 , "body"]

## filtering data 
#### data.loc[condition_for_rows , column] 
#### data.loc[data["year"] == 2015] - all rows for all car made in 2025 
#### data.loc[data.year == 2015 , "trim"] - trim of all car made in 2025 
#### data.loc[(data.year == 2015) & (data.transmission == "automatic")] - multiple condition for all cars made in 2025 and have automatic transmission
#### data.loc[data.model.str.contains("Sor" , case = False , na=False)] - all cars which model contains string "Sor"
#### data.loc[data.model.isin(["Sorento" , "S60"])] - all cars of Sorento or S60 model

In [ ]:
data.loc[data.model.isin(["Sorento" , "S60"])]

### dropping column 
data.drop(column_name) - dropping a column 
data.drop(columns=['body','trim'],inplace = True) - drops body and trim columns , inplace = True apply the changes onto the actual dataset

### adding a column 

data["car_age"] = 2025 - car["year"] - sets a new column called car_age to see all car age in 2025

In [103]:
data["car_age"]= 2025 - data["year"]

In [104]:
data.head()

,year,make,model,trim,body,transmission,vin,state,condition,odometer,color,interior,seller,mmr,sellingprice,saledate,car_age
0,2015,Kia,Sorento,LX,SUV,automatic,5xyktca69fg566472,ca,5.0,16639.0,white,black,kia motors america inc,20500.0,21500.0,Tue Dec 16 2014 12:30:00 GMT-0800 (PST),10
1,2015,Kia,Sorento,LX,SUV,automatic,5xyktca69fg561319,ca,5.0,9393.0,white,beige,kia motors america inc,20800.0,21500.0,Tue Dec 16 2014 12:30:00 GMT-0800 (PST),10
2,2014,BMW,3 Series,328i SULEV,Sedan,automatic,wba3c1c51ek116351,ca,45.0,1331.0,gray,black,financial services remarketing (lease),31900.0,30000.0,Thu Jan 15 2015 04:30:00 GMT-0800 (PST),11
3,2015,Volvo,S60,T5,Sedan,automatic,yv1612tb4f1310987,ca,41.0,14282.0,white,black,volvo na rep/world omni,27500.0,27750.0,Thu Jan 29 2015 04:30:00 GMT-0800 (PST),10
4,2014,BMW,6 Series Gran Coupe,650i,Sedan,automatic,wba6b2c57ed129731,ca,43.0,2641.0,gray,black,financial services remarketing (lease),66000.0,67000.0,Thu Dec 18 2014 12:30:00 GMT-0800 (PST),11

### Renaming a column 
data = data.rename(columns={'current_column_name' : 'new_column_name'})

In [107]:
data = data.rename(columns = {'make' : 'brand'}) #replaces make column to brand 
data.head(2)

,year,brand,model,trim,body,transmission,vin,state,condition,odometer,color,interior,seller,mmr,sellingprice,saledate,car_age
0,2015,Kia,Sorento,LX,SUV,automatic,5xyktca69fg566472,ca,5.0,16639.0,white,black,kia motors america inc,20500.0,21500.0,Tue Dec 16 2014 12:30:00 GMT-0800 (PST),10
1,2015,Kia,Sorento,LX,SUV,automatic,5xyktca69fg561319,ca,5.0,9393.0,white,beige,kia motors america inc,20800.0,21500.0,Tue Dec 16 2014 12:30:00 GMT-0800 (PST),10

In [108]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 558837 entries, 0 to 558836
Data columns (total 17 columns):
 #   Column        Non-Null Count   Dtype
---  ------        --------------   -----
 0   year          558837 non-null  int64
 1   brand         548536 non-null  object
 2   model         548438 non-null  object
 3   trim          548186 non-null  object
 4   body          545642 non-null  object
 5   transmission  493485 non-null  object
 6   vin           558833 non-null  object
 7   state         558837 non-null  object
 8   condition     547017 non-null  float64
 9   odometer      558743 non-null  float64
 10  color         558088 non-null  object
 11  interior      558088 non-null  object
 12  seller        558837 non-null  object
 13  mmr           558799 non-null  float64
 14  sellingprice  558825 non-null  float64
 15  saledate      558825 non-null  object
 16  car_age       558837 non-null  int64
dtypes: float64(4), int64(2), object(11)
memory usage: 72.5+ MB

We want to convert selling date into datetime datatype

In [116]:
data['selling_price_date_time'] = pd.to_datetime(data["saledate"])

SyntaxError: invalid non-printable character U+00A0 (3989359587.py, line 1)

In [ ]:
data.info()